import React from 'react'
import Head from 'next/head'
import Menu from '../Components/menu'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        <h3 className="text">Welcome to our site</h3>
      </main>
    </>
  )
}
